Add support for physical keyboard and mouse (DO NOT MERGE YET)
devkitPro/SDL-mirror pull request #33
Opened 2019-01-17 19:08 UTC by rsn8887

Untested, since I am not at home, and I am not sure I even have compatible keyboard/mouse.

Could be tested with UAE4All2, for example. Or ScummVM...

I am open for comments.

I will try to test it today or on the weekend.

2019-01-17 19:21 UTC, rsn8887 commented
Is there a libnx function for checking whether physical keyboard or mouse are connected? It would help.

2019-01-18 17:32 UTC, rsn8887 commented
This can be merged. It works just fine now.

2019-01-22 22:06 UTC, fincs commented on src/video/switch/SDL_switchkeyboard.c
> +bool keystate[160] = { 0 };
This `160` constant is hardcoded everywhere. Can it be refactored to use e.g. a `#define`?

2019-01-22 22:07 UTC, fincs commented on src/video/switch/SDL_switchkeyboard.c
> +Uint8 locks = 0;
`u8` or `uint8_t`.

2019-01-22 22:08 UTC, fincs commented on src/video/switch/SDL_switchkeyboard.c
> +		if ((hidKeyboardDown(keyCode) || hidKeyboardHeld(keyCode)) && !keystate[i]) {
If down is true then held is also true.

2019-01-22 22:08 UTC, fincs commented on src/video/switch/SDL_switchkeyboard.c
> +		} else if ((hidKeyboardUp(keyCode) || !hidKeyboardHeld(keyCode)) && keystate[i]) {
If up is true then held is false.

2019-01-22 22:09 UTC, fincs commented on src/video/switch/SDL_switchmouse.c
> +	buttons = hidMouseButtonsHeld() | hidMouseButtonsDown();
Same thing here. Simplify this to `buttons = hidMouseButtonsHeld()`

2019-01-22 22:10 UTC, fincs requested changes
.

2019-01-23 03:09 UTC, rsn8887 commented on src/video/switch/SDL_switchkeyboard.c
> +		if ((hidKeyboardDown(keyCode) || hidKeyboardHeld(keyCode)) && !keystate[i]) {
Thanks for the review. This is done.

2019-01-23 03:09 UTC, rsn8887 commented on src/video/switch/SDL_switchkeyboard.c
> +		} else if ((hidKeyboardUp(keyCode) || !hidKeyboardHeld(keyCode)) && keystate[i]) {
Done.

2019-01-23 03:09 UTC, rsn8887 commented on src/video/switch/SDL_switchmouse.c
> +	buttons = hidMouseButtonsHeld() | hidMouseButtonsDown();
Done.

2019-01-23 03:09 UTC, rsn8887 commented on src/video/switch/SDL_switchkeyboard.c
> +Uint8 locks = 0;
Done.

2019-01-23 03:10 UTC, rsn8887 commented on src/video/switch/SDL_switchkeyboard.c
> +bool keystate[160] = { 0 };
Thanks for the review. This is done.

2019-01-23 03:17 UTC, rsn8887 commented
I think I fixed all the comments. I also added empty SDL_QuitKeyboard() and SDL_QuitMouse() functions, for consistency with other ports.

2019-01-23 03:32 UTC, rsn8887 commented on src/video/switch/SDL_switchkeyboard.c
> +bool keystate[160] = { 0 };
Fixed in https://github.com/devkitPro/SDL/pull/33/commits/27115216c99cd97b63af64eda22cb2e5e6034520

2019-01-23 03:33 UTC, rsn8887 commented on src/video/switch/SDL_switchkeyboard.c
> +Uint8 locks = 0;
Fixed in https://github.com/devkitPro/SDL/pull/33/commits/27115216c99cd97b63af64eda22cb2e5e6034520 .

2019-01-23 03:33 UTC, rsn8887 commented on src/video/switch/SDL_switchkeyboard.c
> +		if ((hidKeyboardDown(keyCode) || hidKeyboardHeld(keyCode)) && !keystate[i]) {
Fixed in https://github.com/devkitPro/SDL/pull/33/commits/27115216c99cd97b63af64eda22cb2e5e6034520

2019-01-23 03:33 UTC, rsn8887 commented on src/video/switch/SDL_switchkeyboard.c
> +		} else if ((hidKeyboardUp(keyCode) || !hidKeyboardHeld(keyCode)) && keystate[i]) {
Fixed in https://github.com/devkitPro/SDL/pull/33/commits/27115216c99cd97b63af64eda22cb2e5e6034520

2019-01-23 03:33 UTC, rsn8887 commented on src/video/switch/SDL_switchmouse.c
> +	buttons = hidMouseButtonsHeld() | hidMouseButtonsDown();
Fixed in https://github.com/devkitPro/SDL/pull/33/commits/27115216c99cd97b63af64eda22cb2e5e6034520

2019-01-24 19:34 UTC, rsn8887 commented
Something weird is going on: MousePosition members x and y only report between 0...1280 and 0..720. So either they have to be scaled to 1080p or some other function is missing. velocityX and velocityY seem to depend on the exact time they are being read (they are not integrated).

What is missing is a real measure of "dx" and "dy" to see the difference between last frame and current frame.

Otherwise, mouse motion will not be registered beyond the max and min values of x and y.

2019-01-24 19:53 UTC, TurtleP commented
From what I’ve dealt with regarding the mouse coordinates in 1080p, yes they would need to be scaled. However that’s not up to SDL to handle, the end user must scale it as necessary.

2019-01-24 19:58 UTC, rsn8887 commented
Yes that could be done. 

However, until correct dx and dy values can be read that are not clamped, mouse functionality will be very limited. 

We need a way to get accurate velocities so that mouse motion can be reported even if x and y reach their max or min values.

Current functionality of libnx to read out velocityX and velocityY vie hidMouseRead is broken: It only reports the last velocity values of up to 17 values per frame. See here: 
https://switchbrew.github.io/libnx/structHidMouse.html

We need a nx function to read out all 17 reports to calculate accurate dx and dy values. This would allow relative mouse mode to work.

If that can work, then the clamping could be circumvented, and relative mouse mode would also be possible (currently this is impossible the way libnx is coded).

2019-01-24 20:01 UTC, TurtleP commented
However to clarify: if it is the window itself that changed size, SDL would handle that fine. That’s not the case though, as in docked mode it scales the graphics automatically.

2019-01-24 20:06 UTC, rsn8887 commented
Alternatively hidMouseRead could be modified to report accurate dx, dy values as velocityX and velocityY, by summing over the velocity values of all the new entries.

2019-01-24 21:38 UTC, rsn8887 commented
Shall we re-scale here or not? It would make life much easier until we have a truly working readout of dx and dy values for mouse and can overcome the clamping to 720p.

2019-01-24 21:43 UTC, Cpasjuste commented
I need to take a closer look as my brain is very slow, but i think that when if the windows reports 1080p and libnx 720p for the mouse then scaling should be handled in sdl2.

2019-01-24 22:10 UTC, rsn8887 commented
I hate configure and it's stupid in-source building.

2019-01-24 22:18 UTC, WinterMute commented
@Cpasjuste @rsn8887 how is this kind of thing usually handled in desktop SDL? Should the mouse co-ordinates be dependent a state set by SDL_RenderSetLogicalSize rather than simple docked 1080p vs undocked 720p?

2019-01-24 22:19 UTC, Cpasjuste commented
I really don't  know!

2019-01-25 07:06 UTC, rsn8887 commented
Hmm the official SDL docs say x and y should be relative to the window: 
https://wiki.libsdl.org/SDL_MouseMotionEvent

So that suggests they should be scaled. This is indeed done in the WinRT implementation. However, what about RendererSetLogicalSize? I think that should also be taken into account. But it seems it is not accounted for at least on WinRT.

2019-01-25 08:11 UTC, Cpasjuste commented
I guess it should be handled by the user when RendererSetLogicalSize is used (as the window size doesn't change).

2019-01-25 10:53 UTC, rsn8887 commented
I found a solution for the clamping issue. The solution is to use velocityX and velocityY and limit readout to not more than once per frame.

fixed in 
https://github.com/devkitPro/SDL/pull/33/commits/2b8f718414f6bf2f67adb78250c4f529ebb884e8

2019-01-25 10:55 UTC, rsn8887 commented
I am pretty sure this is the correct way to do it, since it also makes relative mouse mode work correctly (for example for first person shooters, where you don't want mouse motion to be limited in any direction)

2019-01-26 17:53 UTC, rsn8887 commented
This is ready to merge.

2019-01-28 16:12 UTC, rsn8887 commented
@fincs : Do you want to take another look? Also, shall I squash into a single "switch: add support for physical keyboard and mouse" commit?

2019-01-28 17:29 UTC, fincs commented
I'll review it later. Also, we can do the squashing ourselves with the GitHub merge button, don't worry about that.

2019-02-05 12:22 UTC, fincs requested changes
.

2019-02-05 12:22 UTC, fincs commented on src/video/switch/SDL_switchkeyboard.c
> +uint8_t locks = 0;
This should be `static`.

2019-02-05 12:22 UTC, fincs commented on src/video/switch/SDL_switchkeyboard.c
> +bool keystate[NUM_SCANCODES_SWITCH] = { 0 };
This should be `static`.

2019-02-05 12:22 UTC, fincs commented on src/video/switch/SDL_switchkeyboard.c
> +uint8_t switch_scancodes[NUM_SCANCODES_SWITCH] = {
This should be `static const`.

2019-02-05 16:42 UTC, rsn8887 commented on src/video/switch/SDL_switchkeyboard.c
> +uint8_t locks = 0;
fixed in 6201ade922ae72e68aa0e5025c1e91368ab78aed

2019-02-05 16:42 UTC, rsn8887 commented on src/video/switch/SDL_switchkeyboard.c
> +bool keystate[NUM_SCANCODES_SWITCH] = { 0 };
fixed in 6201ade922ae72e68aa0e5025c1e91368ab78aed

2019-02-05 16:42 UTC, rsn8887 commented on src/video/switch/SDL_switchkeyboard.c
> +uint8_t switch_scancodes[NUM_SCANCODES_SWITCH] = {
fixed in 6201ade922ae72e68aa0e5025c1e91368ab78aed

2019-02-05 16:43 UTC, rsn8887 commented
Thanks for the review. I made the changes. I think it should be ready now...

2019-02-05 16:49 UTC, fincs requested changes
.

2019-02-05 16:49 UTC, fincs commented on src/video/switch/SDL_switchkeyboard.c
> +static uint8_t switch_scancodes[NUM_SCANCODES_SWITCH] = {
This is still non-const. I don't see anywhere where you write to it, so it should be const.

2019-02-05 16:55 UTC, rsn8887 commented on src/video/switch/SDL_switchkeyboard.c
> +static uint8_t switch_scancodes[NUM_SCANCODES_SWITCH] = {
oops. Fixed in 77066bbdf51bd9f20079612c660e615f648c57cd

2019-02-05 16:56 UTC, rsn8887 commented
Ok, but now it should finally be ready :)

2019-02-05 16:56 UTC, fincs approved these changes

2019-02-06 04:15 UTC, rsn8887 commented
@Cpasjuste You can squash and merge this now, whenever you have time.

2019-02-10 21:45 UTC, merged